services:

  backend:
    build:
      context: ./interface_times
      dockerfile: api/Dockerfile

    container_name: dashboard_backend
    restart: always

    ports:
      - "5000:5000"

    volumes:
      - ./interface_times/api:/app

    environment:
      DATABASE_URL: postgresql://admin:123456@postgres:5432/dashboard_tcc

    networks:
      - nicol_default


networks:
  nicol_default:
    external: true